package test.java.quickhull;

import static java.lang.String.format;

import org.assertj.core.api.AbstractAssert;
import org.assertj.core.api.Assertions;

import quickhull.jlbEspaciado;

/**
 * {@link jlbEspaciado} specific assertions - Generated by CustomAssertionGenerator.
 */
public class jlbEspaciadoAssert extends AbstractAssert<jlbEspaciadoAssert, jlbEspaciado> {

	/**
	 * Creates a new </code>{@link jlbEspaciadoAssert}</code> to make assertions on actual jlbEspaciado.
	 * @param actual the jlbEspaciado we want to make assertions on.
	 */
	public jlbEspaciadoAssert(jlbEspaciado actual) {
		super(actual, jlbEspaciadoAssert.class);
	}

	/**
	 * An entry point for jlbEspaciadoAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
	 * With a static import, one's can write directly : <code>assertThat(myjlbEspaciado)</code> and get specific assertion with code completion.
	 * @param actual the jlbEspaciado we want to make assertions on.
	 * @return a new </code>{@link jlbEspaciadoAssert}</code>
	 */
	public static jlbEspaciadoAssert assertThat(jlbEspaciado actual) {
		return new jlbEspaciadoAssert(actual);
	}

}
